server:
  port: 3020

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

  routes:
    shopping-web-user:
        path: /api/**
        serviceId: shopping-web-user

    shopping-service:
        path: /notify/**
        serviceId: shopping-service

#logging:
#  file: ./log/shopping-gateway.log
