spring:
  application:
    name: shopping-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: entity.common-config
      profile: dev
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8090