spring:
  application:
    name: shopping-security
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/shopping-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
