spring:
  application:
    name: entity.common-config
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config/
  profiles:
    active:
    - native
server:
  port: 8888
